const { PrismaClient } = require("@prisma/client");
const { PrismaPg } = require("@prisma/adapter-pg");
const { Pool } = require("pg");
require("dotenv").config({ path: require("path").resolve(__dirname, "../.env") });

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

function isBotMessage(msg) {
  // If message is a single continuous string of letters/digits without any space, and length >= 6
  return /^[A-Za-z0-9]{6,}$/.test(msg.trim()) && !msg.includes(" ");
}

function isBotName(name) {
  // Bot names are single word camel/pascal case or random letters like "Vyhvkvub", "Abmymolv", "Wgioga"
  return /^[A-Z][a-z]{3,}$/.test(name.trim()) && !name.includes(" ");
}

async function countStats() {
  const all = await prisma.contactMessage.findMany({
    include: { replies: true },
  });

  const botIds = new Set();
  const botEmails = new Set();

  for (const m of all) {
    if (m.userId || m.replies.length > 0) continue;
    if (m.type === 'DIRECT_MESSAGE') continue;

    if (m.type === 'GENERAL_QUERY' && isBotMessage(m.message)) {
      botIds.add(m.id);
      botEmails.add(m.email.toLowerCase());
    }
  }

  // Also collect newsletter entries generated by the same bot
  for (const m of all) {
    if (m.userId || m.replies.length > 0) continue;
    if (m.type === 'NEWSLETTER' && botEmails.has(m.email.toLowerCase())) {
      botIds.add(m.id);
    }
  }

  console.log(`\n📊 Database Cleanup Breakdown:`);
  console.log(`---------------------------------`);
  console.log(`Total messages in DB:       ${all.length}`);
  console.log(`Identified Bot Spam entries: ${botIds.size}`);
  console.log(`Real Human Messages saved:   ${all.length - botIds.size}`);
}

countStats()
  .catch(console.error)
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
